<!--CREATE DATABASE ERRORMANAGERAPPLICATION;-->

<!--USE ERRORMANAGERAPPLICATION;-->

CREATE TABLE USERS
(
      ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT
    , USERNAME VARCHAR(254)
    , PASSWORD VARCHAR(64)
    , CREATED_AT TIMESTAMP DEFAULT NOW()
    , UPDATED_AT TIMESTAMP
)

CREATE TABLE APPLICATIONS
(
      ID INTEGER PRIMARY KEY AUTO_INCREMENT
    , NAME VARCHAR(255)
    , CREATED_AT TIMESTAMP DEFAULT NOW()
    , USER_ID INTEGER REFERENCES USERS (ID)
);

CREATE TABLE PROFILES
(
    USER_ID BIGINT NOT NULL REFERENCES USERS (ID)
    PROFILES INTEGER
);
