CREATE TRIGGER TRG_SET_FALSE ON USERS AFTER UPDATE
DECLARE @id INTEGER
DECLARE @oldValue BOOLEAN
DECLARE @newValue BOOLEAN

select @newValue = i.IS_ACTIVE, @id = i.ID from inserted i
select @oldValue = d.IS_ACTIVE from deleted d

IF (@newValue <> @oldValue AND id is not null)
    BEGIN
        UPDATE APPLICATIONS SET IS_ACTIVE = FALSE WHERE USER_ID = @id;
    END
;

CREATE INDEX IDX_USERS_USERNAME ON USERS (lower(USERNAME));

CREATE INDEX IDX_APPLICATIONS_NAME ON APPLICATIONS (lower(NAME));

CREATE INDEX IDX_PROFILES_USER_ID ON PROFILES (USER_ID);

