CREATE TABLE LOGS (
    ID SERIAL PRIMARY KEY
  , DESCRIPTION VARCHAR(255) NOT NULL
  , DETAILS VARCHAR(255) NOT NULL
  , ENVIRONMENT VARCHAR(100) NOT NULL
  , LEVEL INTEGER NOT NULL
  , LOG VARCHAR(255) NOT NULL
  , NUMBER_EVENTS INTEGER DEFAULT 1
  , CREATED_AT TIMESTAMP DEFAULT NOW()
  , UPDATED_AT TIMESTAMP
  , APPLICATION_ID INTEGER NOT NULL
)